Add boolean field for default_content_http_proxy in HTTProxy entity
SatelliteQE/nailgun pull request #1254
Opened 2024-11-19 09:08 UTC by Gauravtalreja1

##### Description of changes

Change introduced in https://github.com/Katello/katello/pull/11183

2024-11-20 09:35 UTC, LadislavVasina1 submitted a review, later dismissed

2024-11-23 18:45 UTC, dosas approved these changes

2024-11-25 10:14 UTC, vsedmik requested changes

2024-11-25 10:14 UTC, vsedmik commented on nailgun/entities.py
> +            'default_content_http_proxy': entity_fields.BooleanField(),
```suggestion
            'default_content': entity_fields.BooleanField(),
```
@Gauravtalreja1, could you provide some functional demonstration with ipython? I tried locally with packit VM for https://github.com/Katello/katello/pull/11183 but I don't get the `default_content_http_proxy` on create nor on read back from API. We may need to add it to the ignore list if it's not returned.

Also, I didn't get the setting updated until I used `default_content` in the create call.

2025-01-10 18:16 UTC, dosas commented
@vsedmik How do we proceed here?

2025-01-14 08:50 UTC, vsedmik commented
@dosas looks like https://github.com/Katello/katello/pull/11266 was merged yesterday, which should make this PR in line with product. But I haven't tried it locally yet.
@Gauravtalreja1, would you provide the functional demonstration against packit w/ #11266 instance (or against stream snap once it gets in)?

2025-02-14 09:42 UTC, vsedmik requested changes

2025-02-14 09:42 UTC, vsedmik commented on nailgun/entities.py
> +            ignore.add('content_default_http_proxy')
Tested locally and we need yet a small change (when `attrs is None`):
```
        if attrs is None:
            attrs = self.read_json()
        if ignore is None:
            ignore = set()
        ignore.add('password')
        ignore.add('organization')
        ignore.add('location')
        ignore.add('cacert')
        # Workaround for SAT-30769
        if 'content_default_http_proxy' not in attrs:
            ignore.add('content_default_http_proxy')
```

2025-02-14 09:53 UTC, vsedmik approved these changes

2025-02-14 15:44 UTC, shubhamsg199 approved these changes

2025-02-14 15:44 UTC, merged