Enable download utility selection
SatelliteQE/nailgun pull request #1257
Opened 2024-11-27 12:00 UTC by dosas

##### Description of changes

Add download_utility property to RegistrationCommand

##### Upstream API documentation, plugin, or feature links

Option was added to foreman recently https://github.com/theforeman/foreman/blob/develop/app/controllers/api/v2/registration_commands_controller.rb#L28

2024-11-27 12:05 UTC, Satellite-QE commented
Can one of the admins verify this patch?

2025-01-02 10:51 UTC, vsedmik requested changes
Just a small proposal to consider

2025-01-02 10:51 UTC, vsedmik commented on nailgun/entities.py
> +            'download_utility': entity_fields.StringField(default=''),
I would rather go with
```suggestion
            'download_utility': entity_fields.StringField(choices=('curl', 'wget')),
```
since the apidoc says "Must be one of: `curl`, `wget`" and the field is optional (`curl` is used when missing or `None`)

2025-01-02 10:59 UTC, Gauravtalreja1 commented on nailgun/entities.py
> +            'download_utility': entity_fields.StringField(default=''),
Good suggestion, but I think we'll still need to set `default='curl'` when None is passed

2025-01-02 11:04 UTC, vsedmik commented on nailgun/entities.py
> +            'download_utility': entity_fields.StringField(default=''),
I tried locally even with `download_utility=None` and it passed, but I agree we can state the default for descriptive reasons here.

2025-01-07 07:59 UTC, dosas commented on nailgun/entities.py
> +            'download_utility': entity_fields.StringField(default=''),
Done

2025-01-14 16:53 UTC, dosas commented
@Gauravtalreja1 would you mind to review?

2025-01-27 13:41 UTC, dosas commented
Any news on this?

2025-02-05 19:06 UTC, Gauravtalreja1 approved these changes
ACK, @dosas Do you mind rebasing this PR for merge? 
Thank you!!

2025-02-05 20:01 UTC, Gauravtalreja1 approved these changes

2025-02-05 20:01 UTC, merged