add task_id parameter to TaskTimedOutError and TaskFailedError
SatelliteQE/nailgun pull request #730
Opened 2020-06-04 11:02 UTC by martin-schlossarek

This commits adds a task_id parameter to TaskTimedOutError and TaskFailedError. Knowing the task id helps to handle task related errors.

```
try:
  do_something_task_related()
except TaskFailedError as error
  get_more_information_from_task(error.task_id)
```

At the moment you have to parse the task id from the exception message, which is not very convenient.

2020-10-30 22:17 UTC, rplevka submitted a review, later dismissed
lgtm

2020-11-03 09:43 UTC, ogajduse submitted a review, later dismissed

2021-01-12 20:13 UTC, mshriver commented on nailgun/entity_mixins.py
> +    def __index__(self, message, task_id):
@martin-schlossarek Sorry for the delay in review, but is this supposed to be `__init__`?  Given the use in exception class instantiation within the PR, `__init__` would suffice, but I don't know if you have another intent for handling these exception classes.

Per documentation, `object.__index__()` must return an integer, and at the moment this returns nothing.

2021-01-12 20:15 UTC, mshriver requested changes
I believe the task_id should be handled in `__init__`, not `__index__`. I'm happy to add a commit resolving this since it has been so long since the original PR was opened.

2021-01-13 16:56 UTC, martin-schlossarek commented
> I believe the task_id should be handled in `__init__`, not `__index__`. I'm happy to add a commit resolving this since it has been so long since the original PR was opened.

I force pushed a fixed commit with `__init__`

2021-01-13 17:06 UTC, mshriver submitted a review, later dismissed
Looks good, I don't think any update is needed to the use of `TaskTimedOutError` in `tests/test_entity_mixins.py`. Waiting on Travis results for merge.

Thanks for your contribution @martin-schlossarek

2021-01-13 17:51 UTC, mshriver commented
@martin-schlossarek This ends up failing because of pre-commit formatting enforcement.

https://travis-ci.org/github/SatelliteQE/nailgun/jobs/754321541#L371

If you install the pre-commit hooks locally, and run `pre-commit run --all-files` in your branch, `Black` formatting hook should modify the files so that you can commit them. 

https://pre-commit.com/#3-install-the-git-hook-scripts  Should help you get started if you're not familiar with pre-commit. Note the hook configuration in `.pre-commit-config.yaml`.

2021-01-14 13:05 UTC, martin-schlossarek commented
> @martin-schlossarek This ends up failing because of pre-commit formatting enforcement.
> 
> https://travis-ci.org/github/SatelliteQE/nailgun/jobs/754321541#L371
> 
> If you install the pre-commit hooks locally, and run `pre-commit run --all-files` in your branch, `Black` formatting hook should modify the files so that you can commit them.
> 
> https://pre-commit.com/#3-install-the-git-hook-scripts Should help you get started if you're not familiar with pre-commit. Note the hook configuration in `.pre-commit-config.yaml`.

My local branch had an old `.pre-commit-config.yaml`. Fixed it now.

2021-01-14 19:31 UTC, mshriver approved these changes

2021-01-14 19:51 UTC, JacobCallahan approved these changes

2021-01-14 19:53 UTC, merged