Adding resume and cancel to Foreman Tasks
SatelliteQE/nailgun pull request #810
Opened 2022-01-27 14:09 UTC by Griffin-Sullivan

##### Description of changes

Adding basic methods to bulk cancel or bulk resume Foreman Tasks. Follows conventional POST request methods found in other entities. No impact to existing tests.

##### Upstream API documentation, plugin, or feature links

Not available upstream, but API endpoints can be found in Satellite 7 API doc under Foreman Tasks.

##### Functional demonstration

```python
# Demonstrate cancel function
sync_task = repo.sync(synchronous=False)
entities.ForemanTask().cancel(data={"task_ids": [sync_task['id']]})

# Demonstrate resume function
publish_task = cv.publish(synchronous=False)
# Task gets stopped from reboot
entities.ForemanTask().resume(data={"task_ids": [publish_task['id']]})
```

##### Additional Information

You'll notice that I'm used `task_ids` and passing a list of task ids. That is because these are bulk cancel and bulk resume end points. Passing no data would cancel/resume any cancellable/resumable tasks. You can specify one or multiple tasks using `task_ids`.

I'm also unsure if `synchronous` even makes a difference at these end points, but it seems to be commonly passed in all throughout entities.py.

2022-02-03 09:20 UTC, swadeley approved these changes
ACK

2022-02-14 22:02 UTC, JacobCallahan commented
@Griffin-Sullivan can you try to add the path to the existing nailgun unit tests?

2022-02-15 08:46 UTC, jyejare requested changes
The function names in the entity class must be equal to endpoint names!

2022-02-15 08:46 UTC, jyejare commented on nailgun/entities.py
> +    def cancel(self, synchronous=True, timeout=None, **kwargs):
Rename to the exact name of endpoint:
```suggestion
    def bulk_cancel(self, synchronous=True, timeout=None, **kwargs):
```

2022-02-15 08:46 UTC, jyejare commented on nailgun/entities.py
> +    def resume(self, synchronous=True, timeout=None, **kwargs):
Same here:
```suggestion
    def bulk_resume(self, synchronous=True, timeout=None, **kwargs):
```

2022-02-15 19:35 UTC, Griffin-Sullivan commented
Added unit tests:
```
============================= test session starts ==============================
platform linux -- Python 3.9.10, pytest-6.2.5, py-1.10.0, pluggy-0.13.1
rootdir: /home/gsulliva/Programming/nailgun
plugins: cov-2.12.0, forked-1.3.0
collected 1 item

tests/test_entities.py .                                                 [100%]

-------------- generated xml file: /tmp/tmp-21393nMKpx4C9iiMe.xml --------------
============================== 1 passed in 2.30s ===============================
============================= test session starts ==============================
platform linux -- Python 3.9.10, pytest-6.2.5, py-1.10.0, pluggy-0.13.1
rootdir: /home/gsulliva/Programming/nailgun
plugins: cov-2.12.0, forked-1.3.0
collected 1 item

tests/test_entities.py .                                                 [100%]

-------------- generated xml file: /tmp/tmp-21393CYxG8PLwk40O.xml --------------
============================== 1 passed in 2.25s ===============================
```

2022-02-17 11:58 UTC, jyejare approved these changes

2022-02-21 15:51 UTC, mshriver approved these changes

2022-02-21 15:51 UTC, merged