Fix mirror_on_sync
SatelliteQE/nailgun pull request #811
Opened 2022-01-27 21:42 UTC by latran

Mirror on sync has been changed.  Changing it to reflect what's in repo setup page.  Testing still needs to be done in order to see if it passes and may reflect changes in airgun as well.

2022-01-28 12:24 UTC, jyejare commented
@latran The `mirror_on_sync` ignore PR is already merged https://github.com/SatelliteQE/nailgun/pull/809 please mold your PR accordingly also talk to @Griffin-Sullivan which is looking into this already!

2022-01-28 17:02 UTC, Griffin-Sullivan commented
Tested creating a repo with these changes in 7.0:
```
============================= test session starts ==============================
platform linux -- Python 3.9.9, pytest-6.2.5, py-1.10.0, pluggy-0.13.1
shared_function enabled - OFF - scope:  - storage: file
rootdir: /home/gsulliva/Programming/robottelo, configfile: pyproject.toml
plugins: forked-1.3.0, services-2.2.1, mock-3.6.1, cov-2.12.1, xdist-2.5.0, reportportal-5.0.11, ibutsu-2.0.2
collected 1 item

tests/foreman/api/test_repository.py .                                   [100%]

-------------- generated xml file: /tmp/tmp-11326Xfx42JX5DIE4.xml --------------
============================== 1 passed in 17.54s ==============================
```
Also tested GET in debug with
```python
# enable rh repo
entities.Repository(id=rh_repo).read()
```
And the same for custom repos.

You can also remove the `ignore.add('mirror_on_sync')` in read(), as `mirror_on_sync` is no longer in the init. Katello does all of the assignments for `mirroring_policy` based on what `mirror_on_sync` used to be (see https://github.com/Katello/katello/pull/9834). Component owners will need to update any tests that set `mirror_on_sync` now.

2022-02-01 07:27 UTC, jyejare requested changes
Overall looks good, but please add/modify unit tests for 2 new fields. Currently, the unit tests are passing because the `mirror_on_sync` is still available in POST request(depreciated form).

2022-02-01 15:14 UTC, latran commented
@jyejare are you talking about the `test` dir in nailgun or are you talking about the tests cases in api in robottelo?

2022-02-04 14:59 UTC, latran commented
@jyejare I looked at the unit test cases.  There's not really test cases that focuses specifically on `mirror_on_sync` from before so I'm not sure where to add `mirroring_policy` or if that's even necessary.

2022-02-08 15:27 UTC, jyejare commented
@latran yeah, probably its not required, coz `mirror_on_sync` was ignored while reading but probably thats not required for mirroring_policy.

2022-02-09 16:41 UTC, mshriver approved these changes

2022-02-09 16:41 UTC, merged