Remove codecov dependency
SatelliteQE/nailgun pull request #914
Opened 2023-04-14 15:36 UTC by pnovotny

codecov is no longer in PyPI.

More info:
https://about.codecov.io/blog/message-regarding-the-pypi-package/

2023-04-14 16:17 UTC, pnovotny commented
Ok, this looks like a stalemate. `codecov` package is no longer in PyPI, but nailgun uses it in the Code Quality (3.8) check - Test Nailgun Coverage.

2023-04-17 08:50 UTC, lhellebr commented
I don't have an opinion on whether we need it or not. But if we do, maybe get it from some other soure?

2023-04-17 08:51 UTC, pondrejk submitted a review, later dismissed

2023-04-27 10:49 UTC, jyejare requested changes
Dont remove the codecov package but just update the version to the latest one. The codecov is not entirely removed but they removed 2.1.12 version. So use 2.1.13 version

See my PR works for codecov installation https://github.com/SatelliteQE/nailgun/pull/915/files#diff-2b4945591edfeaa4cf4d3f155e66d4b43d1bda7a55d881d5cf3107f1b05abbbc

2023-04-28 14:19 UTC, jyejare commented
@pnovotny ping, see my last comment !

2023-04-28 19:14 UTC, pnovotny commented
@jyejare sorry for the late reply. Good news that they've kept the package. I've updated the requirements to codecov 2.1.13

2023-05-02 07:17 UTC, jyejare approved these changes

2023-05-02 07:22 UTC, jyejare commented
@pnovotny The codecov warning to fix the integration between this repo and code coverage upload is now enabled.

2023-05-02 07:22 UTC, jyejare commented
Merging this PR as its failing checks for other PRs.

2023-05-02 07:24 UTC, merged