Add TablePreferences entity
SatelliteQE/nailgun pull request #928
Opened 2023-06-06 14:31 UTC by lhellebr

##### Description of changes
Added TablePreferences entity.

##### Functional demonstration

Shouldn't cause regression, this test uses search and hasn't changed:
```
$ pytest tests/foreman/api/test_contentview.py::test_positive_admin_user_actions
================================================================= test session starts =================================================================
platform linux -- Python 3.9.16, pytest-7.3.1, pluggy-1.0.0 -- /home/lhellebr/git/robottelo/venv/bin/python
Mandatory Requirements Available: jinja2==3.1.2 broker[docker]==0.3.2 pytest-xdist==3.3.1 wrapanapi==3.5.15 requests==2.31.0 pytest-reportportal==5.1.8
Optional Requirements Available: pre-commit==3.3.2 redis==4.5.5 manage>=0.1.13 sphinx==7.0.1
cachedir: .pytest_cache
shared_function enabled - OFF - scope:  - storage: file
rootdir: /home/lhellebr/git/robottelo
configfile: pytest.ini
plugins: cov-3.0.0, services-2.2.1, xdist-3.2.1, reportportal-5.1.7, mock-3.10.0, ibutsu-2.2.4
collected 1 item                                                                                                                                      

tests/foreman/api/test_contentview.py::test_positive_admin_user_actions PASSED                                                                  [100%]

================================================================= 1 passed in 56.59s ==================================================================

```
The same happens when I change that test to use ServerConfig explicitly, and don't change anything else (so it doesn't specify the new argument).

This is a new test using it:
```
$ pytest tests/foreman/api/test_user.py::TestUser::test_positive_table_preferences
================================================================= test session starts =================================================================
platform linux -- Python 3.9.16, pytest-7.3.1, pluggy-1.0.0 -- /home/lhellebr/git/robottelo/venv/bin/python
Mandatory Requirements Available: jinja2==3.1.2 pytest-xdist==3.3.1 broker[docker]==0.3.2 requests==2.31.0 wrapanapi==3.5.15 pytest-reportportal==5.1.8
Optional Requirements Available: redis==4.5.5 pre-commit==3.3.2 manage>=0.1.13 sphinx==7.0.1
cachedir: .pytest_cache
shared_function enabled - OFF - scope:  - storage: file
rootdir: /home/lhellebr/git/robottelo
configfile: pytest.ini
plugins: cov-3.0.0, services-2.2.1, xdist-3.2.1, reportportal-5.1.7, mock-3.10.0, ibutsu-2.2.4
collected 1 item                                                                                                                                      

tests/foreman/api/test_user.py::TestUser::test_positive_create_with_username 
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> PDB set_trace (IO-capturing turned off) >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
> /home/lhellebr/git/robottelo/tests/foreman/api/test_user.py(428)test_positive_create_with_username()
-> assert hasattr(tp, 'name')
(Pdb) c

>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> PDB continue (IO-capturing resumed) >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
PASSED                                                             [100%]

================================================================= 1 passed in 58.13s ==================================================================

```

2023-06-07 09:16 UTC, lhellebr commented
`make docs-html` fails and it also happens in master -> failure unrelated

2023-06-08 14:38 UTC, lhellebr commented
The dependent robottelo PR has been merged. Can we also merge this?

2023-06-12 08:55 UTC, jyejare requested changes
The `make docs` failure is related to the change in the table-preferences entity only, please fix it !

Also, update unit tests for the the new class!

2023-06-12 10:44 UTC, lhellebr commented
Yes, this failure is a real one, I'll fix it. Previously, already the test invocation has been failing.

2023-06-12 11:03 UTC, jyejare commented
Patch coverage is only 26% , so you should now add unit tests.

2023-06-12 14:26 UTC, lhellebr commented
Yes, I was working on it, it just took a little while.
The report doesn't seem to be updated yet (let's wait a little bit, I don't know how to force refresh) but I think it should be ok now.

2023-06-14 17:13 UTC, sambible approved these changes
Any reason for not using PRT? Looks good either way. Also, you aren't alone on forgetting to add tests for Nailgun PRs :)

2023-06-15 08:25 UTC, lhellebr commented
trigger: test-robottelo
pytest: tests/foreman/api/test_contentview.py -k test_positive_admin_user_actions

2023-06-15 09:42 UTC, jyejare approved these changes

2023-06-20 06:56 UTC, omkarkhatavkar commented
> Who knows why I still don't see any PRT results. But I think we can merge. The test using this is merged already!

PRT results get overridden once you add a new commit in the code.

2023-06-20 06:56 UTC, omkarkhatavkar commented
trigger: test-robottelo
pytest: tests/foreman/api/test_contentview.py -k test_positive_admin_user_actions

2023-06-23 07:03 UTC, omkarkhatavkar approved these changes

2023-06-23 07:03 UTC, merged